Initial Commit

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,82 +1,85 @@
 sudo: required
 dist: trusty
-
-#workaround for https://github.com/travis-ci/travis-ci/issues/5227
-addons:
-  hostname: pegasus-tester
-
 os: linux
-language: generic
+language: minimal
 cache:
   directories:
   - depends/built
+  - depends/work
   - depends/sdk-sources
-  - $HOME/.ccache
+  - "$HOME/.ccache"
 env:
   global:
-    - MAKEJOBS=-j3
-    - RUN_TESTS=false
-    - CHECK_DOC=0
-    - CHECK_LOGPRINT=0
-    - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
-    - CCACHE_SIZE=100M
-    - CCACHE_TEMPDIR=/tmp/.ccache-temp
-    - CCACHE_COMPRESS=1
-    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
-    - SDK_URL=https://bitcoincore.org/depends-sources/sdks
-    - PYTHON_DEBUG=1
-    - WINEDEBUG=fixme-all
+  - SDK_URL=https://bitcoincore.org/depends-sources/sdks
+  - CCACHE_SIZE=200M
+  - CCACHE_TEMPDIR=/tmp/.ccache-temp
+  - CCACHE_COMPRESS=1
+  - MAKEJOBS="-j2"
+  - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
+  - BASE_PACKAGES="zlib1g-dev zip git build-essential libtool autotools-dev automake
+    pkg-config libevent-dev libssl-dev bsdmainutils curl libboost-all-dev libdb4.8-dev
+    libdb4.8++-dev libminiupnpc-dev libzmq3-dev libprotobuf-dev protobuf-compiler
+    libqrencode-dev"
   matrix:
-# ARM
-    - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" CHECK_DOC=1 CHECK_LOGPRINT=1 GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
-# Win32
-    - HOST=i686-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="NO_QT=1" PACKAGES="python3 nsis g++-mingw-w64-i686 wine1.6 bc" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-reduce-exports"
-# 32-bit + dash
-    - HOST=i686-pc-linux-gnu PACKAGES="g++-multilib bc python3-zmq" DEP_OPTS="NO_QT=1" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++" USE_SHELL="/bin/dash" PYZMQ=true
-# Win64
-    - HOST=x86_64-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="NO_QT=1" PACKAGES="python3 nsis g++-mingw-w64-x86-64 wine1.6 bc" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-reduce-exports"
-# pegasusd
-    - HOST=x86_64-unknown-linux-gnu PACKAGES="bc python3-zmq" DEP_OPTS="NO_QT=1 NO_UPNP=1 DEBUG=1" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports CPPFLAGS=-DDEBUG_LOCKORDER" PYZMQ=true
-
-# No wallet
-#    - HOST=x86_64-unknown-linux-gnu PACKAGES="python3" DEP_OPTS="NO_WALLET=1" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
-# Cross-Mac
-    - HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python-dev" BITCOIN_CONFIG="--enable-reduce-exports" OSX_SDK=10.11 GOAL="deploy"
-
+  - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" OPT="NO_QT=1" CONF="--without-gui"
+  - HOST=aarch64-linux-gnu PACKAGES="g++-aarch64-linux-gnu" OPT="NO_QT=1" CONF="--without-gui"
+  - HOST=i686-w64-mingw32 PACKAGES="g++-mingw-w64-i686 mingw-w64-i686-dev"
+  - HOST=x86_64-w64-mingw32 PACKAGES="g++-mingw-w64-x86-64 mingw-w64-x86-64-dev"
+  - HOST=x86_64-unknown-linux-gnu PACKAGES=""
+  - HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin
+    libz-dev libbz2-dev libtiff-tools python-dev" OSX_SDK=10.11
 before_install:
-    - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
+- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" |
+  sed "s|::|:|g")
 install:
-    - if [ "$PYZMQ" = "true" ]; then pip install pyzmq --user ; fi
-    - if [ -n "$PPA" ]; then travis_retry sudo add-apt-repository "$PPA" -y; fi
-    - if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ; fi
-    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
-    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi
+- sudo add-apt-repository -y ppa:bitcoin/bitcoin
+- sudo apt-get update
+- travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $BASE_PACKAGES
+- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends
+  --no-upgrade -qq $PACKAGES; fi
 before_script:
-    - unset CC; unset CXX
-    - if [ "$CHECK_DOC" = 1 ]; then contrib/devtools/check-doc.py; fi
-    - if [ "$CHECK_LOGPRINT" = 1 ]; then contrib/devtools/logprint-scanner.py; fi
-    - mkdir -p depends/SDKs depends/sdk-sources
-    - if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
-    - if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
-    - make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS
+- unset CC; unset CXX
+- cd $TRAVIS_BUILD_DIR
+- mkdir -p depends/SDKs depends/sdk-sources
+- if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
+  curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz;
+  fi
+- if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
+  tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
 script:
-    - export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
-    - if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
-    - OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
-    - BITCOIN_CONFIG_ALL="--disable-dependency-tracking --prefix=$TRAVIS_BUILD_DIR/depends/$HOST --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
-    - depends/$HOST/native/bin/ccache --max-size=$CCACHE_SIZE
-    - test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
-    - ./configure --cache-file=config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)
-    - make distdir PACKAGE=bitcoin VERSION=$HOST
-    - cd bitcoin-$HOST
-    - ./configure --cache-file=../config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)
-    - make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL V=1 ; false )
-    - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
-    - if [ "$RUN_TESTS" = "true" ]; then make $MAKEJOBS check VERBOSE=1; fi
-    #- if [ "$RUN_TESTS" = "true" ]; then qa/pull-tester/rpc-tests.py --coverage; fi
-after_script:
-    - echo $TRAVIS_COMMIT_RANGE
-    - echo $TRAVIS_COMMIT_LOG
-notifications:
-  slack:
-    secure: w22XjHoG/3xplxWzddS9Ma7i99Q/hq4FA3Q56xS+RtO2vlFgDT+eDzCppstdx96mn2/4e+/V1aiQ4E6GVEvJMeldqSUhPv9OBnKR0KJVAOwu4haNXt+0ZeQFt8lIndKB5cMVyOJkoq6peGoHNXslClM0lGuBn7g7VC2QPQYNWrJNrrGL7IiVb6fNOIKHWcC4URkzSvXAhO/WIqSSlmKxAAx0B2oEsM8LhdAbcjbp7Sm7zH87TIVGBZ7iTVuMc6B9+SfClbE8bBuRtvjTX57Q4UUZzn0zDtKdPdCte0oXdaQF4RdVim9mDodBGIpDo+avW4WL7EE+AK33fs94pwH5bu0LEandR/aeEvVpbSpQ2XsEKSe+6woizgl5i4GXFVZduJF62y/o1f+S/zC3qW9lIEEpiZc4PpX7pDy30X3p6S5nMrW7T/zNh+SjLhS1VP6XKdQtpD3WRCY4GKZYammZhk5RbOy3jTXAahIXuttWdhl/Q3Rb5VqfFJWlrG/qQXt73qOk2/DgJnABxXE6gnWO4MpHAq+kdomNR+nod4HeXI3DOk1wRuQRVoW1rSjiqQd6Db+TP56RKYgt4M4csOD0DG9G+W0AOtZkuKHTeoEtmQfkKFPZLYAQumv41cDN2UE9gKIECmvJSevj4sMCDTWtozKWqay/W4n2+cmhbzmGflY=
+- OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
+- |
+  timeout 3500 ./build.sh
+    # Convert the timeout exit code to 0.
+    RESULT=$?; if [ $RESULT -eq 0 ] || [ $RESULT -eq 142 ]; then true; else false; fi;
+before_deploy:
+# Set up git user name and tag this commit
+      - git config --local user.name "pegasus-project"
+      - git config --local user.email "dev@pegasuscoin.org"
+      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
+      - "./pre-deploy.sh"
+deploy:
+  provider: releases
+  api_key:
+    secure: NGE60l7Lbs74ihAOqqiiD18vkVcYI0SDc3fIt3NBKfHiprvHTnldDNNrOIOuIDsg0LII65JJo1NKf7JJB86bfhqSrLyDnkeCmJRXjjSYjzKaAcLbRvixTSx9bVkHwOTTYXEhFpp9dZKjcqinPxnuO6FQf7bH0xiF6WtVQeK8oMjY3JcQZwOssbof5XSBbPaQLCFSWDyhJ7jdOqMprTd9Agq5RdxjRaaT9bYiykbqLbI6KgH5kNbkLcu734iYdWCZr+tfngUYc2teGwCkF7LYl6o2OPoW0byyitfDqjlBKIBCxPQwsFXL1QphyNiYWMlpU5yA9XqgSz5+WHhhPzO1GAOKTRiE+8Cpv7Pf55F1Z39N36howhhKS9c0mvAdxDrEkk5T2tLkdHOwrja7sgn374uXgI2u8ucb7W7iBfQO3tZ1tNBihj5+ks3Rv5nup8TgmJGcu4MadFqzGZH6uaj7cFRMZZWRVaKgQGdox0snk/Wmh0hcaTfIJv9Fg4ioEOhH/ecOOGdJIgLCL0ccmp/ynIRMF4Q3jGeAsch0MImTK6WkP9VJwOOSuM2daB/MVCJISyHa945BbP6fou9CneqH/X/3G5EbXes+8Itcdg/SabWIW7PGvTdWn7T1g5DYAn4MN1UgRiI+hQqL3oVRqmVyOu2a+Q97HxzF1lbhHfQCfus=
+  file: out/**/zip/*
+  skip_cleanup: true
+  on:
+    repo: pegasus-project/pegasus
+  on:
+    tags: true  
+deploy:
+  provider: s3
+  access_key_id: AKIAIKPTCZAG4GFH5EPQ
+  secret_access_key:
+    secure: sNmtJ8YcKrKo+MXYWRDfbSsHlTnGP1DQPMmUmDR/zE89toduGP9A4u4+xEM3jnK1bUj/dBPtF05zeQynKva9CHmD6/+pz5sX14rgXYDPPE0YB0b1qhgCp7TKa77bEU2B50291puR+XhftFvvWiPg0PMWup7ZZYfySmJF6WIU/dwyT0Pw8I+piapNjOT38xzvYp/OGJSltX5K+ME8W6s/sMsWCok4evvZx5zQ+Bh3I1A5q0QyirjM1JCxz06p1jC0BENgqNHGRXaxgXzrUx24lqB/AoOl9qrvtTfiKxfB1lJLMt59RLUnJ4ol4CvIbd7AQBD8lg8aVraUCs5jgqE5Vaccvn+9CNe5BCSDioiNzv7JVu6yLuPkMnwSagvUeItZIEhWqvcP6FpnJAC/J3Gn2LhN8zJWadYAhvicaUUhKEY+vFdc7HncYpqfiJlNWl90FZ73k8hMM3JayDebhjSpQ29KMfYMVUpjnrnpKxCASFz5d4vpxPlOlZFqwAPBnEPInVGi2IoyWR3+2Cfhi7tQNOZ7TgTUFo3Q6eLfl48F92JEMQQPACytBeTrI7Kdtk5FHxSnKAF5E3o2wR72iym9YedfLjQSCISkcqbozzTB9cY5JLSvZUgmD26wXK63ApPf+LHKe5Q0VJCh/daPSD6K22t25FXeSr8lYkAHPsLpew4=
+  bucket: pegasus
+  skip_cleanup: true
+  local_dir:  $TRAVIS_BUILD_DIR/out/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
+  upload-dir: $TRAVIS_JOB_NUMBER
+  acl: public_read
+  on:
+    repo: pegasus-project/pegasus
+    cache_control: "max-age=21600"
+    on:
+      all_branches: true
